apiVersion: v2
name: katta-server
home: https://github.com/shift7-ch/katta-helm
icon: https://katta.cloud/katta-logo.png
description: Helm chart for deploying Katta Server with optional Keycloak, PostgreSQL and MinIO
type: application
version: 1.0.0
appVersion: "latest"
kubeVersion: ">=1.27.0-0"
sources:
  - https://github.com/shift7-ch/katta-helm
  - https://github.com/shift7-ch/katta-server
keywords:
  - katta
  - katta-server
  - cryptomator-hub-fork
